### ISSUE TITLE
question: params for some of the processors

### ISSUE THREAD

**Issue by gedw99** [wasmvision/wasmvision#37]
I am a designer and some of the processors are pretty awful in terms of the styles they are meant to represent.

I was wondering if there is one day going to be the ability to feed in params to try to make them a bit more sane ? 

I have not had time yet to dig into the depths of how they really work as a neural net.

**Comment by deadprogram** [comment]
I assume you are referring to the fast neural style transfer models?

Those are pre-trained models, see https://github.com/onnx/models/blob/main/validated/vision/style_transfer/fast_neural_style/README.md for more info those.

TLDR: you would have to modify the models themselves AFAIK to change how they operate. I am pretty sure that the only param that you could try is the resizing before the style transfer.
